(autoload 'git-blame-color-scale                "git-blame" "" nil)
(autoload 'git-blame-random-pop                 "git-blame" "" nil 'macro)
(autoload 'git-blame-mode                       "git-blame" "" t)
(autoload 'git-blame-mode-on                    "git-blame" "" nil)
(autoload 'git-blame-mode-off                   "git-blame" "" nil)
(autoload 'git-reblame                          "git-blame" "" t)
(autoload 'git-blame-run                        "git-blame" "" nil)
(autoload 'remove-git-blame-text-properties     "git-blame" "" nil)
(autoload 'git-blame-cleanup                    "git-blame" "" nil)
(autoload 'git-blame-update-region              "git-blame" "" nil)
(autoload 'git-blame-sentinel                   "git-blame" "" nil)
(autoload 'git-blame-filter                     "git-blame" "" nil)
(autoload 'git-blame-parse                      "git-blame" "" nil)
(autoload 'git-blame-new-commit                 "git-blame" "" nil)
(autoload 'git-blame-create-overlay             "git-blame" "" nil)
(autoload 'git-blame-add-info                   "git-blame" "" nil)
(autoload 'git-blame-get-info                   "git-blame" "" nil)
(autoload 'git-blame-current-commit             "git-blame" "" nil)
(autoload 'git-describe-commit                  "git-blame" "" nil)
(autoload 'git-blame-identify                   "git-blame" "" t)
(autoload 'git-blame-after-change               "git-blame" "" nil)
(autoload 'git-blame-enq-update                 "git-blame" "" nil)
(autoload 'git-blame-delayed-update             "git-blame" "" nil)
(provide 'git-blame-mode-epackage-autoloads)
